version: 0.0
os: linux
permissions:
  - object: /home/ec2-user/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
files: 
  - source: /
    destination: /home/ec2-user/deploy
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300 
      runas: ec2-user 
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 80
      runas: ec2-user
  ValidateService:
    - location: scripts/ValidateService.sh
      timeout: 30
      runas: ec2-user
