version: '2'
services:
    web:
        image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/devops-test
        container_name: flask-devops
        ports:
            - "5000:5000"
        volumes:
            - .:/code
 
