version: '2'
services:
    web:
        image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/devops-v1
        container_name: flask-devops
        ports:
            - "5000:5000"
        tty: true
        stdin_open: true
        volumes:
            - .:/code
        command:
          - app.py
